// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-I51yIsKqzHMBxsOK2PLsr2HQZYqWn0',
    appId: '1:416056594956:web:651eef851bac8ddaec5429',
    messagingSenderId: '416056594956',
    projectId: 'fir-bookmark-9bc67',
    authDomain: 'fir-bookmark-9bc67.firebaseapp.com',
    storageBucket: 'fir-bookmark-9bc67.appspot.com',
    measurementId: 'G-MSM46Z5M36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmuwaNhfZwLI20MLc_NLrfOEh_mtgU34M',
    appId: '1:416056594956:android:44eeb870f0025120ec5429',
    messagingSenderId: '416056594956',
    projectId: 'fir-bookmark-9bc67',
    storageBucket: 'fir-bookmark-9bc67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROweEBQIjd__cGNMTfwqiY8gjw2aH35w',
    appId: '1:416056594956:ios:8f62d80d68ee1f36ec5429',
    messagingSenderId: '416056594956',
    projectId: 'fir-bookmark-9bc67',
    storageBucket: 'fir-bookmark-9bc67.appspot.com',
    iosClientId: '416056594956-lok6d99u52vqgv4n80ma5jto6f8qabg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBookmark',
  );
}
